/**
 * ScaffoldAgent.ts
 *
 * Generates a complete Expo + Convex project from scratch using the BNA AI agent.
 * No template cloning required — every file is generated by the AI based on the
 * project description.
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs/promises';
import { TokenStore } from '../auth/TokenStore';
import { ConvexProjectManager } from '../convex/ConvexProjectManager';
import { BNA_API_BASE_URL } from '../constants';
import { StreamingArtifactParser } from '../agent/StreamingArtifactParser';
import { logger } from '../utils/logger';
import * as crypto from 'crypto';

/** Minimal package.json used to bootstrap dependency installation */
const BOOTSTRAP_PACKAGE_JSON = {
  name: 'bna-app',
  version: '1.0.0',
  main: 'expo-router/entry',
  scripts: {
    start: 'expo start',
    android: 'expo run:android',
    ios: 'expo run:ios',
  },
  dependencies: {
    expo: '~54.0.0',
    'expo-router': '~4.0.0',
    'expo-dev-client': '~5.0.0',
    'expo-haptics': '~14.0.0',
    'expo-secure-store': '~14.0.0',
    react: '18.3.1',
    'react-native': '0.76.0',
    'react-native-reanimated': '~3.16.0',
    'react-native-safe-area-context': '~5.0.0',
    'react-native-screens': '~4.4.0',
    'react-native-gesture-handler': '~2.21.0',
    'react-native-keyboard-controller': '~1.15.2',
    convex: '^1.27.0',
    '@convex-dev/auth': '^0.0.90',
    '@expo/vector-icons': '^14.0.0',
    'lucide-react-native': '^0.460.0',
  },
  devDependencies: {
    '@types/react': '~18.3.0',
    typescript: '~5.7.0',
  },
};

/** Minimal tsconfig to satisfy TypeScript in the generated project */
const BOOTSTRAP_TSCONFIG = {
  extends: 'expo/tsconfig.base',
  compilerOptions: {
    strict: true,
    paths: { '@/*': ['./*'] },
  },
};

/**
 * The system prompt injected as the first user message to prime the AI for
 * full project generation (not incremental editing).
 */
function buildScaffoldPrompt(projectName: string, description: string): string {
  const slug = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

  return `
You are BNA. Generate a complete Expo React Native + Convex app called "${projectName}".

CRITICAL RULES — read before doing anything:
- This is a BRAND NEW empty project. There are NO existing files to view or edit.
- Do NOT call any tools (view, edit, deploy, npmInstall). Tools are disabled.
- Do NOT write a plan or outline. Do NOT say "I'll start with...".
- Start writing boltArtifact tags IMMEDIATELY with the first file.
- Every file must contain 100% complete, working code — no placeholders, no "// TODO".

App description: ${description || `A ${projectName} app`}

Write ALL of these files in this exact order, each as a separate boltAction inside one boltArtifact:

1.  theme/colors.ts — invent a unique color palette for THIS specific app. Export COLORS, RADIUS, SPACING. Never reuse yellows/blacks.
2.  components/ui/button.tsx — Pressable with Reanimated spring scale + expo-haptics, variants: primary/secondary/outline/ghost/danger, sizes: sm/md/lg, loading + disabled states
3.  components/ui/text.tsx — typography variants: h1/h2/h3/body/bodyLg/label/caption, accepts color/align/numberOfLines/style props
4.  components/ui/input.tsx — TextInput styled with theme colors, label, error, secure support
5.  components/ui/card.tsx — Pressable card with shadow, variants
6.  components/ui/spinner.tsx — ActivityIndicator using COLORS.primary
7.  convex/schema.ts — defineSchema with ...authTables, users table (email/name/image/isAnonymous), plus tables needed for the app features
8.  convex/auth.ts — convexAuth with Google and GitHub providers
9.  convex/auth.config.ts — auth config with CONVEX_SITE_URL
10. convex/http.ts — httpRouter with auth.addHttpRoutes
11. convex/users.ts — getCurrentUser helper, getUser query, getCurrentUserId query
12. convex/[feature].ts — mutations/queries for the app's core features
13. components/auth/authentication.tsx — sign in form using UI components
14. components/auth/singout.tsx — sign out button
15. app/_layout.tsx — root layout: ConvexProvider + ConvexAuthProvider, font loading, auth redirect logic
16. app/index.tsx — redirects to /(home) or /sign-in based on auth
17. app/+not-found.tsx — 404 screen
18. app/(home)/_layout.tsx — NativeTabs layout with proper icons
19. app/(home)/index.tsx — main home screen (core app feature)
20. app/(home)/settings.tsx — settings/profile screen with sign out
21. app.json — MUST have: name="${projectName}", slug="${slug}", scheme="${slug}", ios.bundleIdentifier="com.bna.${slug.replace(/-/g, '')}", android.package="com.bna.${slug.replace(/-/g, '')}", newArchEnabled=true, plugins=["expo-router","expo-secure-store","@convex-dev/auth/expo-router-plugin"]
22. expo-env.d.ts — \`/// <reference types="expo-router/types" />\`
23. eslint.config.js — basic ESLint flat config
24. eas.json — EAS build profiles (development/preview/production)

Start the boltArtifact now. No commentary before it.
`.trim();
}

export interface ScaffoldProgress {
  message: string;
  filesWritten: number;
  totalEstimated: number;
}

export type ScaffoldCallback = (progress: ScaffoldProgress) => void;

/**
 * Scaffolds a new BNA project by asking the AI to generate all files from scratch.
 */
export class ScaffoldAgent {
  private filesWritten = 0;
  private abortController: AbortController | null = null;

  constructor(
    private readonly tokenStore: TokenStore,
    private readonly projectManager: ConvexProjectManager,
  ) {}

  /**
   * Generate a full project at `projectDir`.
   *
   * @param projectDir   Absolute path where project files will be written
   * @param projectName  Human-readable project name
   * @param description  What the app does (used to guide AI generation)
   * @param onProgress   Optional progress callback
   */
  async scaffold(
    projectDir: string,
    projectName: string,
    description: string,
    onProgress?: ScaffoldCallback,
  ): Promise<void> {
    this.filesWritten = 0;
    this.abortController = new AbortController();

    // 1. Create the project directory
    await fs.mkdir(projectDir, { recursive: true });

    // 2. Write the bootstrap files that npm install needs up front
    await this.writeBootstrapFiles(projectDir, projectName);
    onProgress?.({
      message: 'Bootstrapping project structure...',
      filesWritten: 0,
      totalEstimated: 25,
    });

    // 3. Call the BNA API to generate all source files
    await this.generateWithAI(projectDir, projectName, description, onProgress);
  }

  abort(): void {
    this.abortController?.abort();
  }

  // ─── Private helpers ────────────────────────────────────────────────────

  private async writeBootstrapFiles(
    projectDir: string,
    projectName: string,
  ): Promise<void> {
    const slug = projectName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    const pkg = {
      ...BOOTSTRAP_PACKAGE_JSON,
      name: slug,
    };

    await fs.writeFile(
      path.join(projectDir, 'package.json'),
      JSON.stringify(pkg, null, 2),
      'utf-8',
    );

    await fs.writeFile(
      path.join(projectDir, 'tsconfig.json'),
      JSON.stringify(BOOTSTRAP_TSCONFIG, null, 2),
      'utf-8',
    );

    await fs.writeFile(
      path.join(projectDir, '.gitignore'),
      [
        'node_modules/',
        '.expo/',
        'dist/',
        '.env.local',
        'ios/',
        'android/',
        '*.jks',
        '*.p8',
        '*.p12',
        '*.key',
        '*.mobileprovision',
        '*.orig.*',
        'web-build/',
      ].join('\n') + '\n',
      'utf-8',
    );

    // Create directory structure so the AI doesn't have to
    const dirs = [
      'app',
      'app/(home)',
      'components/auth',
      'components/ui',
      'convex',
      'theme',
    ];
    for (const dir of dirs) {
      await fs.mkdir(path.join(projectDir, dir), { recursive: true });
    }
  }

  private async generateWithAI(
    projectDir: string,
    projectName: string,
    description: string,
    onProgress?: ScaffoldCallback,
  ): Promise<void> {
    const token = await this.tokenStore.getConvexAuthToken();
    const accessToken = await this.tokenStore.getConvexAccessToken();
    const teamSlug = await this.tokenStore.getTeamSlug();
    const userId = await this.tokenStore.getUserId();

    if (!token || !accessToken || !teamSlug) {
      throw new Error(
        'Not authenticated. Please sign in and connect Convex first.',
      );
    }

    const chatId = crypto.randomUUID();
    const scaffoldPrompt = buildScaffoldPrompt(projectName, description);

    const body = {
      messages: [
        {
          id: crypto.randomUUID(),
          role: 'user',
          content: scaffoldPrompt,
          parts: [{ type: 'text', text: scaffoldPrompt }],
        },
      ],
      firstUserMessage: true,
      chatInitialId: chatId,
      token: accessToken,
      teamSlug,
      deploymentName: undefined,
      shouldDisableTools: true,
      recordRawPromptsForDebugging: false,
      collapsedMessages: false,
      userId: userId || undefined,
      featureFlags: { enableResend: false },
    };

    const response = await fetch(`${BNA_API_BASE_URL}/api/chat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(body),
      signal: this.abortController?.signal,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`AI generation failed (${response.status}): ${text}`);
    }

    if (!response.body) {
      throw new Error('No response body from AI');
    }

    await this.processStream(response.body, projectDir, onProgress);
  }

  private async processStream(
    body: ReadableStream<Uint8Array>,
    projectDir: string,
    onProgress?: ScaffoldCallback,
  ): Promise<void> {
    const reader = body.getReader();
    const decoder = new TextDecoder();

    const parser = new StreamingArtifactParser({
      onFileComplete: async (file) => {
        try {
          await this.writeProjectFile(projectDir, file.filePath, file.content);
          this.filesWritten++;
          onProgress?.({
            message: `Generating ${path.basename(file.filePath)}...`,
            filesWritten: this.filesWritten,
            totalEstimated: 25,
          });
        } catch (err) {
          logger.error(`Failed to write ${file.filePath}:`, err);
        }
      },
    });

    let buffer = '';

    try {
      while (true) {
        if (this.abortController?.signal.aborted) break;

        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (!line.trim()) continue;
          if (line.length < 2) continue;

          const type = line[0];
          const data = line.slice(2);

          if (type === '0') {
            // Text delta — feed into artifact parser
            try {
              const text = JSON.parse(data) as string;
              parser.feed(text);
            } catch {
              parser.feed(data);
            }
          }
          // We don't handle tool calls during scaffold — pure generation mode
        }
      }
    } finally {
      reader.releaseLock();
      parser.flush();
    }
  }

  private async writeProjectFile(
    projectDir: string,
    filePath: string,
    content: string,
  ): Promise<void> {
    // Normalize paths — strip /home/project/ prefix if the AI uses it
    let relative = filePath;
    for (const prefix of ['/home/project/', '/home/project']) {
      if (relative.startsWith(prefix)) {
        relative = relative.slice(prefix.length);
        break;
      }
    }
    if (relative.startsWith('/')) {
      relative = relative.slice(1);
    }

    const fullPath = path.join(projectDir, relative);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, content, 'utf-8');
    logger.debug(`Scaffold wrote: ${relative}`);
  }
}
